add github actions

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,48 +1,57 @@
 name: .NET
 
 on:
-    pull_request:
-        branches: ["master"]
+  pull_request:
+    branches: ["master"]
 
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v4
-      with:
-        dotnet-version: 8.0.x
-    - name: Restore dependencies
-      run: dotnet restore
-    - name: Build all projects with error annotations
-      continue-on-error: true
-      run: |
-        build_failed=false
-        for project in $(find . -regex '.*/Занятие (4|5|6|7)/.*\.csproj'); do
-          echo "Restoring dependencies for project: $project"
-          dotnet restore "$project"
+      - uses: actions/checkout@v4
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: 6.0.x
+      - name: Check .NET version
+        run: dotnet --version
+      - name: List .NET SDKs
+        run: dotnet --list-sdks
+      - name: Find .csproj files
+        run: |
+          echo "Looking for .csproj files in specified directories..."
+          $(find . -regex '\./Занятие\ [4-7]/.*\.csproj')
+      # - name: Build all projects with error annotations
+      #   continue-on-error: true
+      #   run: |
+      #     echo "start"
+      #     build_failed=false
 
-          echo "Building project: $project"
-          build_output=$(dotnet build "$project" --no-restore  || true)
+      #     mapfile -t projects < <(find ./Занятие\ 4 ./Занятие\ 5 ./Занятие\ 6 ./Занятие\ 7 -name '*.csproj')
 
-          if [[ $build_output == *"error"* ]]; then
-            build_failed=true
-          fi
+      #     for project in "${projects[@]}"; do
+      #       echo "Restoring dependencies for project: \"$project\""
+      #       dotnet restore "$project"
 
-          echo "$build_output"| awk '!seen[$0]++' | while read -r line; do
-            if [[ "$line" =~ ^(.*[a-zA-Z0-9_/.]+)\(([0-9]+),([0-9]+)\):\ error\ (.*)$ ]]; then
-              file="${BASH_REMATCH[1]}"
-              line_number="${BASH_REMATCH[2]}"
-              column_number="${BASH_REMATCH[3]}"
-              error_message="${BASH_REMATCH[4]}"
-              echo "::error file=$file,line=$line_number,col=$column_number::$error_message"
-            fi
-          done
-        done
+      #       echo "Building project: \"$project\""
+      #       build_output=$(dotnet build "$project" --no-restore  || true)
 
-        echo "build_failed=$build_failed" >> $GITHUB_ENV
-    - name: Fail if there were build errors
-      if: env.build_failed == 'true' || ${{ failure() }}
-      run: exit 1
+      #       if [[ $build_output == *"error"* ]]; then
+      #         build_failed=true
+      #       fi
 
+      #       echo "$build_output"| awk '!seen[$0]++' | while read -r line; do
+      #         if [[ "$line" =~ ^(.*[a-zA-Z0-9_/.]+)\(([0-9]+),([0-9]+)\):\ error\ (.*)$ ]]; then
+      #           file="${BASH_REMATCH[1]}"
+      #           line_number="${BASH_REMATCH[2]}"
+      #           column_number="${BASH_REMATCH[3]}"
+      #           error_message="${BASH_REMATCH[4]}"
+      #           echo "::error file=$file,line=$line_number,col=$column_number::$error_message"
+      #         fi
+      #       done
+      #     done
+      #     echo "end"
+      #     echo "build_failed=$build_failed" >> $GITHUB_ENV
+      # - name: Fail if there were build errors
+      #   if: env.build_failed == 'true' || ${{ failure() }}
+      #   run: exit 1
